### ISSUE TITLE
Cover do not appear

### ISSUE THREAD

**Issue by DiogoFerrari** [Madh93/conky-spotify#1]
For some reason, the cover do not appear, although the place holder image does. Would you have any idea what should I look at to fix this?

**Comment by Madh93** [comment]
Hi! I commited some changes, tell me if now works fine.

**Comment by DiogoFerrari** [comment]
Working perfect. Thank you !

**Comment by v0idpwn** [comment]
No cover neither placeholder image here. What could be wrong?
