### ISSUE TITLE
cover.sh fails if no wget-log exists

### ISSUE THREAD

**Issue by BarkleyIII** [Madh93/conky-spotify#13]
(linux newbie here)
the covers are loading correctly into /conky-spotify/covers and /conky-spotify/current.
but the widget is missing the album image. This message appears after running conky -c conky-spotify-small:
rm: cannot remove 'wget-log': No such file or directory
any help? the rest seems to be working fine.

_Originally posted by @highonskooma in https://github.com/Madh93/conky-spotify/issues/7#issuecomment-660666119_

**Comment by highonskooma** [comment]
It worked! Thank you for the help.
Although I'm still having problems displaying the cover on with conky-spotify-small, conky-spotify-medium is working.
Great job.

**Comment by BarkleyIII** [comment]
try changing the position in line 41 from 0,587 to 0,0 ;)

**Comment by Madh93** [comment]
Fixed.
